// Code generated by entc, DO NOT EDIT.

package insurance

const (
	// Label holds the string label denoting the insurance type in the database.
	Label = "insurance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInsurancecompany holds the string denoting the insurancecompany field in the database.
	FieldInsurancecompany = "insurancecompany"

	// EdgeInsurancePatientrights holds the string denoting the insurancepatientrights edge name in mutations.
	EdgeInsurancePatientrights = "InsurancePatientrights"

	// Table holds the table name of the insurance in the database.
	Table = "insurances"
	// InsurancePatientrightsTable is the table the holds the InsurancePatientrights relation/edge.
	InsurancePatientrightsTable = "patientrights"
	// InsurancePatientrightsInverseTable is the table name for the Patientrights entity.
	// It exists in this package in order to avoid circular dependency with the "patientrights" package.
	InsurancePatientrightsInverseTable = "patientrights"
	// InsurancePatientrightsColumn is the table column denoting the InsurancePatientrights relation/edge.
	InsurancePatientrightsColumn = "InsurancePatientrights_id"
)

// Columns holds all SQL columns for insurance fields.
var Columns = []string{
	FieldID,
	FieldInsurancecompany,
}
