// Code generated by entc, DO NOT EDIT.

package insurance

import (
	"github.com/PON/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Insurancecompany applies equality check predicate on the "Insurancecompany" field. It's identical to InsurancecompanyEQ.
func Insurancecompany(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyEQ applies the EQ predicate on the "Insurancecompany" field.
func InsurancecompanyEQ(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyNEQ applies the NEQ predicate on the "Insurancecompany" field.
func InsurancecompanyNEQ(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyIn applies the In predicate on the "Insurancecompany" field.
func InsurancecompanyIn(vs ...string) predicate.Insurance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInsurancecompany), v...))
	})
}

// InsurancecompanyNotIn applies the NotIn predicate on the "Insurancecompany" field.
func InsurancecompanyNotIn(vs ...string) predicate.Insurance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInsurancecompany), v...))
	})
}

// InsurancecompanyGT applies the GT predicate on the "Insurancecompany" field.
func InsurancecompanyGT(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyGTE applies the GTE predicate on the "Insurancecompany" field.
func InsurancecompanyGTE(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyLT applies the LT predicate on the "Insurancecompany" field.
func InsurancecompanyLT(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyLTE applies the LTE predicate on the "Insurancecompany" field.
func InsurancecompanyLTE(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyContains applies the Contains predicate on the "Insurancecompany" field.
func InsurancecompanyContains(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyHasPrefix applies the HasPrefix predicate on the "Insurancecompany" field.
func InsurancecompanyHasPrefix(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyHasSuffix applies the HasSuffix predicate on the "Insurancecompany" field.
func InsurancecompanyHasSuffix(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyEqualFold applies the EqualFold predicate on the "Insurancecompany" field.
func InsurancecompanyEqualFold(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldInsurancecompany), v))
	})
}

// InsurancecompanyContainsFold applies the ContainsFold predicate on the "Insurancecompany" field.
func InsurancecompanyContainsFold(v string) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldInsurancecompany), v))
	})
}

// HasInsurancePatientrights applies the HasEdge predicate on the "InsurancePatientrights" edge.
func HasInsurancePatientrights() predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InsurancePatientrightsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InsurancePatientrightsTable, InsurancePatientrightsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInsurancePatientrightsWith applies the HasEdge predicate on the "InsurancePatientrights" edge with a given conditions (other predicates).
func HasInsurancePatientrightsWith(preds ...predicate.Patientrights) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InsurancePatientrightsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InsurancePatientrightsTable, InsurancePatientrightsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Insurance) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Insurance) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Insurance) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		p(s.Not())
	})
}
