// Code generated by entc, DO NOT EDIT.

package abilitypatientrights

const (
	// Label holds the string label denoting the abilitypatientrights type in the database.
	Label = "abilitypatientrights"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOperative holds the string denoting the operative field in the database.
	FieldOperative = "operative"
	// FieldMedicalSupplies holds the string denoting the medicalsupplies field in the database.
	FieldMedicalSupplies = "medical_supplies"
	// FieldExamine holds the string denoting the examine field in the database.
	FieldExamine = "examine"

	// EdgeAbilitypatientrightsPatientrightstype holds the string denoting the abilitypatientrightspatientrightstype edge name in mutations.
	EdgeAbilitypatientrightsPatientrightstype = "AbilitypatientrightsPatientrightstype"

	// Table holds the table name of the abilitypatientrights in the database.
	Table = "abilitypatientrights"
	// AbilitypatientrightsPatientrightstypeTable is the table the holds the AbilitypatientrightsPatientrightstype relation/edge.
	AbilitypatientrightsPatientrightstypeTable = "patientrightstypes"
	// AbilitypatientrightsPatientrightstypeInverseTable is the table name for the Patientrightstype entity.
	// It exists in this package in order to avoid circular dependency with the "patientrightstype" package.
	AbilitypatientrightsPatientrightstypeInverseTable = "patientrightstypes"
	// AbilitypatientrightsPatientrightstypeColumn is the table column denoting the AbilitypatientrightsPatientrightstype relation/edge.
	AbilitypatientrightsPatientrightstypeColumn = "Abilitypatientrights_id"
)

// Columns holds all SQL columns for abilitypatientrights fields.
var Columns = []string{
	FieldID,
	FieldOperative,
	FieldMedicalSupplies,
	FieldExamine,
}
