// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/PON/app/ent/abilitypatientrights"
	"github.com/PON/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// AbilitypatientrightsDelete is the builder for deleting a Abilitypatientrights entity.
type AbilitypatientrightsDelete struct {
	config
	hooks      []Hook
	mutation   *AbilitypatientrightsMutation
	predicates []predicate.Abilitypatientrights
}

// Where adds a new predicate to the delete builder.
func (ad *AbilitypatientrightsDelete) Where(ps ...predicate.Abilitypatientrights) *AbilitypatientrightsDelete {
	ad.predicates = append(ad.predicates, ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AbilitypatientrightsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ad.hooks) == 0 {
		affected, err = ad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AbilitypatientrightsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ad.mutation = mutation
			affected, err = ad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ad.hooks) - 1; i >= 0; i-- {
			mut = ad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AbilitypatientrightsDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AbilitypatientrightsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: abilitypatientrights.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: abilitypatientrights.FieldID,
			},
		},
	}
	if ps := ad.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
}

// AbilitypatientrightsDeleteOne is the builder for deleting a single Abilitypatientrights entity.
type AbilitypatientrightsDeleteOne struct {
	ad *AbilitypatientrightsDelete
}

// Exec executes the deletion query.
func (ado *AbilitypatientrightsDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{abilitypatientrights.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AbilitypatientrightsDeleteOne) ExecX(ctx context.Context) {
	ado.ad.ExecX(ctx)
}
