// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/PON/app/ent/medicalrecordstaff"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Medicalrecordstaff is the model entity for the Medicalrecordstaff schema.
type Medicalrecordstaff struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MedicalrecordstaffQuery when eager-loading is set.
	Edges MedicalrecordstaffEdges `json:"edges"`
}

// MedicalrecordstaffEdges holds the relations/edges for other nodes in the graph.
type MedicalrecordstaffEdges struct {
	// MedicalrecordstaffPatientrights holds the value of the MedicalrecordstaffPatientrights edge.
	MedicalrecordstaffPatientrights []*Patientrights
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MedicalrecordstaffPatientrightsOrErr returns the MedicalrecordstaffPatientrights value or an error if the edge
// was not loaded in eager-loading.
func (e MedicalrecordstaffEdges) MedicalrecordstaffPatientrightsOrErr() ([]*Patientrights, error) {
	if e.loadedTypes[0] {
		return e.MedicalrecordstaffPatientrights, nil
	}
	return nil, &NotLoadedError{edge: "MedicalrecordstaffPatientrights"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Medicalrecordstaff) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Medicalrecordstaff fields.
func (m *Medicalrecordstaff) assignValues(values ...interface{}) error {
	if m, n := len(values), len(medicalrecordstaff.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	m.ID = int(value.Int64)
	values = values[1:]
	return nil
}

// QueryMedicalrecordstaffPatientrights queries the MedicalrecordstaffPatientrights edge of the Medicalrecordstaff.
func (m *Medicalrecordstaff) QueryMedicalrecordstaffPatientrights() *PatientrightsQuery {
	return (&MedicalrecordstaffClient{config: m.config}).QueryMedicalrecordstaffPatientrights(m)
}

// Update returns a builder for updating this Medicalrecordstaff.
// Note that, you need to call Medicalrecordstaff.Unwrap() before calling this method, if this Medicalrecordstaff
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Medicalrecordstaff) Update() *MedicalrecordstaffUpdateOne {
	return (&MedicalrecordstaffClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (m *Medicalrecordstaff) Unwrap() *Medicalrecordstaff {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Medicalrecordstaff is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Medicalrecordstaff) String() string {
	var builder strings.Builder
	builder.WriteString("Medicalrecordstaff(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Medicalrecordstaffs is a parsable slice of Medicalrecordstaff.
type Medicalrecordstaffs []*Medicalrecordstaff

func (m Medicalrecordstaffs) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
