// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/PON/app/ent/patientrecord"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Patientrecord is the model entity for the Patientrecord schema.
type Patientrecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PatientrecordQuery when eager-loading is set.
	Edges PatientrecordEdges `json:"edges"`
}

// PatientrecordEdges holds the relations/edges for other nodes in the graph.
type PatientrecordEdges struct {
	// PatientrecordPatientrights holds the value of the PatientrecordPatientrights edge.
	PatientrecordPatientrights []*Patientrights
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PatientrecordPatientrightsOrErr returns the PatientrecordPatientrights value or an error if the edge
// was not loaded in eager-loading.
func (e PatientrecordEdges) PatientrecordPatientrightsOrErr() ([]*Patientrights, error) {
	if e.loadedTypes[0] {
		return e.PatientrecordPatientrights, nil
	}
	return nil, &NotLoadedError{edge: "PatientrecordPatientrights"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Patientrecord) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Patientrecord fields.
func (pa *Patientrecord) assignValues(values ...interface{}) error {
	if m, n := len(values), len(patientrecord.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pa.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Name", values[0])
	} else if value.Valid {
		pa.Name = value.String
	}
	return nil
}

// QueryPatientrecordPatientrights queries the PatientrecordPatientrights edge of the Patientrecord.
func (pa *Patientrecord) QueryPatientrecordPatientrights() *PatientrightsQuery {
	return (&PatientrecordClient{config: pa.config}).QueryPatientrecordPatientrights(pa)
}

// Update returns a builder for updating this Patientrecord.
// Note that, you need to call Patientrecord.Unwrap() before calling this method, if this Patientrecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Patientrecord) Update() *PatientrecordUpdateOne {
	return (&PatientrecordClient{config: pa.config}).UpdateOne(pa)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pa *Patientrecord) Unwrap() *Patientrecord {
	tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Patientrecord is not a transactional entity")
	}
	pa.config.driver = tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Patientrecord) String() string {
	var builder strings.Builder
	builder.WriteString("Patientrecord(")
	builder.WriteString(fmt.Sprintf("id=%v", pa.ID))
	builder.WriteString(", Name=")
	builder.WriteString(pa.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Patientrecords is a parsable slice of Patientrecord.
type Patientrecords []*Patientrecord

func (pa Patientrecords) config(cfg config) {
	for _i := range pa {
		pa[_i].config = cfg
	}
}
