// Code generated by entc, DO NOT EDIT.

package medicalrecordstaff

const (
	// Label holds the string label denoting the medicalrecordstaff type in the database.
	Label = "medicalrecordstaff"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeMedicalrecordstaffPatientrights holds the string denoting the medicalrecordstaffpatientrights edge name in mutations.
	EdgeMedicalrecordstaffPatientrights = "MedicalrecordstaffPatientrights"

	// Table holds the table name of the medicalrecordstaff in the database.
	Table = "medicalrecordstaffs"
	// MedicalrecordstaffPatientrightsTable is the table the holds the MedicalrecordstaffPatientrights relation/edge.
	MedicalrecordstaffPatientrightsTable = "patientrights"
	// MedicalrecordstaffPatientrightsInverseTable is the table name for the Patientrights entity.
	// It exists in this package in order to avoid circular dependency with the "patientrights" package.
	MedicalrecordstaffPatientrightsInverseTable = "patientrights"
	// MedicalrecordstaffPatientrightsColumn is the table column denoting the MedicalrecordstaffPatientrights relation/edge.
	MedicalrecordstaffPatientrightsColumn = "Medicalrecordstaff_id"
)

// Columns holds all SQL columns for medicalrecordstaff fields.
var Columns = []string{
	FieldID,
}
