// Code generated by entc, DO NOT EDIT.

package patientrecord

const (
	// Label holds the string label denoting the patientrecord type in the database.
	Label = "patientrecord"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgePatientrecordPatientrights holds the string denoting the patientrecordpatientrights edge name in mutations.
	EdgePatientrecordPatientrights = "PatientrecordPatientrights"

	// Table holds the table name of the patientrecord in the database.
	Table = "patientrecords"
	// PatientrecordPatientrightsTable is the table the holds the PatientrecordPatientrights relation/edge.
	PatientrecordPatientrightsTable = "patientrights"
	// PatientrecordPatientrightsInverseTable is the table name for the Patientrights entity.
	// It exists in this package in order to avoid circular dependency with the "patientrights" package.
	PatientrecordPatientrightsInverseTable = "patientrights"
	// PatientrecordPatientrightsColumn is the table column denoting the PatientrecordPatientrights relation/edge.
	PatientrecordPatientrightsColumn = "Patientrecord_id"
)

// Columns holds all SQL columns for patientrecord fields.
var Columns = []string{
	FieldID,
	FieldName,
}
