/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAbilitypatientrightsEdges,
    EntAbilitypatientrightsEdgesFromJSON,
    EntAbilitypatientrightsEdgesFromJSONTyped,
    EntAbilitypatientrightsEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAbilitypatientrights
 */
export interface EntAbilitypatientrights {
    /**
     * Examine holds the value of the "Examine" field.
     * @type {string}
     * @memberof EntAbilitypatientrights
     */
    examine?: string;
    /**
     * MedicalSupplies holds the value of the "MedicalSupplies" field.
     * @type {string}
     * @memberof EntAbilitypatientrights
     */
    medicalSupplies?: string;
    /**
     * Operative holds the value of the "Operative" field.
     * @type {string}
     * @memberof EntAbilitypatientrights
     */
    operative?: string;
    /**
     * 
     * @type {EntAbilitypatientrightsEdges}
     * @memberof EntAbilitypatientrights
     */
    edges?: EntAbilitypatientrightsEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntAbilitypatientrights
     */
    id?: number;
}

export function EntAbilitypatientrightsFromJSON(json: any): EntAbilitypatientrights {
    return EntAbilitypatientrightsFromJSONTyped(json, false);
}

export function EntAbilitypatientrightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAbilitypatientrights {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'examine': !exists(json, 'Examine') ? undefined : json['Examine'],
        'medicalSupplies': !exists(json, 'MedicalSupplies') ? undefined : json['MedicalSupplies'],
        'operative': !exists(json, 'Operative') ? undefined : json['Operative'],
        'edges': !exists(json, 'edges') ? undefined : EntAbilitypatientrightsEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntAbilitypatientrightsToJSON(value?: EntAbilitypatientrights | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Examine': value.examine,
        'MedicalSupplies': value.medicalSupplies,
        'Operative': value.operative,
        'edges': EntAbilitypatientrightsEdgesToJSON(value.edges),
        'id': value.id,
    };
}


