/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientrights,
    EntPatientrightsFromJSON,
    EntPatientrightsFromJSONTyped,
    EntPatientrightsToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntInsuranceEdges
 */
export interface EntInsuranceEdges {
    /**
     * InsurancePatientrights holds the value of the InsurancePatientrights edge.
     * @type {Array<EntPatientrights>}
     * @memberof EntInsuranceEdges
     */
    insurancePatientrights?: Array<EntPatientrights>;
}

export function EntInsuranceEdgesFromJSON(json: any): EntInsuranceEdges {
    return EntInsuranceEdgesFromJSONTyped(json, false);
}

export function EntInsuranceEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntInsuranceEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'insurancePatientrights': !exists(json, 'insurancePatientrights') ? undefined : ((json['insurancePatientrights'] as Array<any>).map(EntPatientrightsFromJSON)),
    };
}

export function EntInsuranceEdgesToJSON(value?: EntInsuranceEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'insurancePatientrights': value.insurancePatientrights === undefined ? undefined : ((value.insurancePatientrights as Array<any>).map(EntPatientrightsToJSON)),
    };
}


