/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMedicalrecordstaffEdges,
    EntMedicalrecordstaffEdgesFromJSON,
    EntMedicalrecordstaffEdgesFromJSONTyped,
    EntMedicalrecordstaffEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMedicalrecordstaff
 */
export interface EntMedicalrecordstaff {
    /**
     * 
     * @type {EntMedicalrecordstaffEdges}
     * @memberof EntMedicalrecordstaff
     */
    edges?: EntMedicalrecordstaffEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntMedicalrecordstaff
     */
    id?: number;
}

export function EntMedicalrecordstaffFromJSON(json: any): EntMedicalrecordstaff {
    return EntMedicalrecordstaffFromJSONTyped(json, false);
}

export function EntMedicalrecordstaffFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMedicalrecordstaff {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntMedicalrecordstaffEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntMedicalrecordstaffToJSON(value?: EntMedicalrecordstaff | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntMedicalrecordstaffEdgesToJSON(value.edges),
        'id': value.id,
    };
}


