/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientrecordEdges,
    EntPatientrecordEdgesFromJSON,
    EntPatientrecordEdgesFromJSONTyped,
    EntPatientrecordEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientrecord
 */
export interface EntPatientrecord {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntPatientrecord
     */
    name?: string;
    /**
     * 
     * @type {EntPatientrecordEdges}
     * @memberof EntPatientrecord
     */
    edges?: EntPatientrecordEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPatientrecord
     */
    id?: number;
}

export function EntPatientrecordFromJSON(json: any): EntPatientrecord {
    return EntPatientrecordFromJSONTyped(json, false);
}

export function EntPatientrecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientrecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntPatientrecordEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPatientrecordToJSON(value?: EntPatientrecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntPatientrecordEdgesToJSON(value.edges),
        'id': value.id,
    };
}


