/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntInsurance,
    EntInsuranceFromJSON,
    EntInsuranceFromJSONTyped,
    EntInsuranceToJSON,
    EntMedicalrecordstaff,
    EntMedicalrecordstaffFromJSON,
    EntMedicalrecordstaffFromJSONTyped,
    EntMedicalrecordstaffToJSON,
    EntPatientrecord,
    EntPatientrecordFromJSON,
    EntPatientrecordFromJSONTyped,
    EntPatientrecordToJSON,
    EntPatientrightstype,
    EntPatientrightstypeFromJSON,
    EntPatientrightstypeFromJSONTyped,
    EntPatientrightstypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientrightsEdges
 */
export interface EntPatientrightsEdges {
    /**
     * 
     * @type {EntInsurance}
     * @memberof EntPatientrightsEdges
     */
    patientrightsInsurance?: EntInsurance;
    /**
     * 
     * @type {EntMedicalrecordstaff}
     * @memberof EntPatientrightsEdges
     */
    patientrightsMedicalrecordstaff?: EntMedicalrecordstaff;
    /**
     * 
     * @type {EntPatientrecord}
     * @memberof EntPatientrightsEdges
     */
    patientrightsPatientrecord?: EntPatientrecord;
    /**
     * 
     * @type {EntPatientrightstype}
     * @memberof EntPatientrightsEdges
     */
    patientrightsPatientrightstype?: EntPatientrightstype;
}

export function EntPatientrightsEdgesFromJSON(json: any): EntPatientrightsEdges {
    return EntPatientrightsEdgesFromJSONTyped(json, false);
}

export function EntPatientrightsEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientrightsEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientrightsInsurance': !exists(json, 'PatientrightsInsurance') ? undefined : EntInsuranceFromJSON(json['PatientrightsInsurance']),
        'patientrightsMedicalrecordstaff': !exists(json, 'PatientrightsMedicalrecordstaff') ? undefined : EntMedicalrecordstaffFromJSON(json['PatientrightsMedicalrecordstaff']),
        'patientrightsPatientrecord': !exists(json, 'PatientrightsPatientrecord') ? undefined : EntPatientrecordFromJSON(json['PatientrightsPatientrecord']),
        'patientrightsPatientrightstype': !exists(json, 'PatientrightsPatientrightstype') ? undefined : EntPatientrightstypeFromJSON(json['PatientrightsPatientrightstype']),
    };
}

export function EntPatientrightsEdgesToJSON(value?: EntPatientrightsEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientrightsInsurance': EntInsuranceToJSON(value.patientrightsInsurance),
        'patientrightsMedicalrecordstaff': EntMedicalrecordstaffToJSON(value.patientrightsMedicalrecordstaff),
        'patientrightsPatientrecord': EntPatientrecordToJSON(value.patientrightsPatientrecord),
        'patientrightsPatientrightstype': EntPatientrightstypeToJSON(value.patientrightsPatientrightstype),
    };
}


