/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientrights,
    EntPatientrightsFromJSON,
    EntPatientrightsFromJSONTyped,
    EntPatientrightsToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientrecordEdges
 */
export interface EntPatientrecordEdges {
    /**
     * PatientrecordPatientrights holds the value of the PatientrecordPatientrights edge.
     * @type {Array<EntPatientrights>}
     * @memberof EntPatientrecordEdges
     */
    patientrecordPatientrights?: Array<EntPatientrights>;
}

export function EntPatientrecordEdgesFromJSON(json: any): EntPatientrecordEdges {
    return EntPatientrecordEdgesFromJSONTyped(json, false);
}

export function EntPatientrecordEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientrecordEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientrecordPatientrights': !exists(json, 'patientrecordPatientrights') ? undefined : ((json['patientrecordPatientrights'] as Array<any>).map(EntPatientrightsFromJSON)),
    };
}

export function EntPatientrecordEdgesToJSON(value?: EntPatientrecordEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientrecordPatientrights': value.patientrecordPatientrights === undefined ? undefined : ((value.patientrecordPatientrights as Array<any>).map(EntPatientrightsToJSON)),
    };
}


